### PR TITLE
feat(status): add status for vpcId and private/publicSubnetId

### PR DESCRIPTION
**Pull request by haarchri**
### Description of your changes
- add new status for vpcId
- add new status for privateSubnetId and publicSubnetId
- re-order the patches

Fixes #

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

new status fields available:

```
--- PASS: kuttl (344.81s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/case (344.35s)
PASS
10:04:16 [ OK ] running automated tests
```

```
  status:
    conditions:
    - lastTransitionTime: "2024-01-26T11:26:04Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2024-01-26T09:31:09Z"
      reason: Available
      status: "True"
      type: Ready
    connectionDetails:
      lastPublishedTime: "2024-01-26T09:28:06Z"
    privateSubnetIds:
    - subnet-0415d100bdc1af806
    - subnet-0fe4596df8cdf3075
    publicSubnetIds:
    - subnet-05e0114de10069cc7
    - subnet-0ba1fc98978556e25
    securityGroupIds:
    - sg-0aa44bd34033dc678
    subnetIds:
    - subnet-05e0114de10069cc7
    - subnet-0ba1fc98978556e25
    - subnet-0415d100bdc1af806
    - subnet-0fe4596df8cdf3075
    vpcId: vpc-0a0265e20e09c62ec
```

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Can you please expand `How has this code been tested` part to demonstrate tested values propagation?

**Comment by haarchri** [comment]
done

**Review by ytsarev — APPROVED** [review]
LGTM

**Pull request merged**
